### ISSUE TITLE
Demon Crashing 

### ISSUE THREAD

**Issue by Findblocks** [Pink2Dev/Pink2#32]
Hi guys 

Local version: 2.2.3.2 CryptoROX 

Random Crashes  on the new version ? am i the only one will get a the log soon

**Comment by laakie** [comment]
Got the same issue here. No errors. it just stops
"v2.2.3.2 CryptoROX"

**Comment by aistrych** [comment]
@laakie Thanks for the info. We know the source of the issue and already working on a fix. In meantime you can use version 2.2.3.1 or 2.2.3.2 with parameter usentp=0 in your config.

**Comment by aistrych** [comment]
@laakie New release (2.3.0.0) should fix crashing issue. Please check if it's fixed for you.

**Comment by laakie** [comment]
seems to be going well now with 'usentp=0 '

**Comment by aistrych** [comment]
@laakie Well, when you use it with `usentp=0` NTP is disabled so it can't crash (it shouldn't anyway). But to test if crashing issue is fixed in 2.3.0.0 you have to use it without that configuration.
It works for us but maybe there are people with some issues. If no one will report crashing issues in a week or so i will close that issue. Is that ok for you?
